#!/bin/bash

WRAPPER="$1"; shift
case "$WRAPPER" in
    serioussam)

        # Required for audio to work on Wayland, hooks into local pulse server.
        if test -S "${XDG_RUNTIME_DIR//snap.$SNAP_NAME/pulse}"/native; then
            export PULSE_SERVER=unix:"${XDG_RUNTIME_DIR//snap.$SNAP_NAME/pulse}"/native
        fi
        exec "$SNAP"/usr/bin/serioussam "$@"
        ;;
    serioussam.se)

        # Required for audio to work on Wayland, hooks into local pulse server.
        if test -S "${XDG_RUNTIME_DIR//snap.$SNAP_NAME/pulse}"/native; then
            export PULSE_SERVER=unix:"${XDG_RUNTIME_DIR//snap.$SNAP_NAME/pulse}"/native
        fi
        exec "$SNAP"/usr/bin/serioussamse "$@"
        ;;
esac
